--- 
apiVersion: v1
kind: Pod
metadata: 
  name: my-nginx-pod
spec: 
  containers: 
    - 
      image: "nginx:latest"
      name: my-nginx-container
      ports: 
        - 
          containerPort: 80
          protocal: TCP
